# 60 prompts: 15 knowledge, 15 instruction, 15 extraction, 15 reasoning. Checks: contains_all / contains_any / exact_num / regex / rubric
K = [
 ("k01","What is the boiling point of water at sea level in Kelvin? Number only.", ("contains_any",["373"])),
 ("k02","Which river flows through Baghdad? One word.", ("contains_any",["Tigris"])),
 ("k03","What is the SI unit of electrical capacitance, and who is it named after? One line.", ("contains_all",["farad","Faraday"])),
 ("k04","Which company designed the Zen CPU microarchitecture? One word.", ("contains_any",["AMD","Advanced Micro Devices"])),
 ("k05","What year did the Apollo 11 landing take place, and who was the command module pilot who stayed in orbit? One line.", ("contains_all",["1969","Collins"])),
 ("k06","In PCI Express, what does the term 'lane' refer to, and how many differential pairs does one lane use? One line.", ("contains_any",["two","2 differential","two differential","2 pairs","two pairs"])),
 ("k07","What is the chemical formula of ozone? Formula only.", ("contains_any",["O3","O₃"])),
 ("k08","Name the programming language created by Guido van Rossum and the year it was first released. One line.", ("contains_all",["Python","1991"])),
 ("k09","Which planet in our solar system has the shortest day? One word.", ("contains_any",["Jupiter"])),
 ("k10","What is the name of the protocol that resolves an IPv4 address to a MAC address on a local network? Acronym only.", ("contains_any",["ARP"])),
 ("k11","Who composed the opera 'The Magic Flute', and in what year did it premiere? One line.", ("contains_all",["Mozart","1791"])),
 ("k12","What does the 'S' in 'RAID 5' NOT stand for? Answer only: what does the number 5 denote, briefly.", ("contains_any",["parity","distributed parity","striping with parity","level"])),
 ("k13","How many bits are in an IPv6 address? Number only.", ("contains_any",["128"])),
 ("k14","What is the largest moon of Saturn? One word.", ("contains_any",["Titan"])),
 ("k15","Which Linux syscall creates a new process by duplicating the calling process? One word.", ("contains_any",["fork"])),
]
I = [
 ("i01","Reply with the word 'yes' in uppercase, three times, separated by commas, and nothing else.", ("regex", r"^\s*YES,\s*YES,\s*YES\s*$")),
 ("i02","Write exactly two sentences about the Moon. The second sentence must start with the word 'However'.", ("rubric","two sentences, second begins with However")),
 ("i03","Give me a JSON object with keys 'name' (string), 'age' (integer), 'tags' (array of exactly three strings). No prose, no code fence.", ("json_keys",{"name":str,"age":int,"tags":3})),
 ("i04","Count from 10 down to 1, one number per line, then write 'liftoff' on its own line. Nothing else.", ("regex", r"^\s*10\n9\n8\n7\n6\n5\n4\n3\n2\n1\nliftoff\s*$")),
 ("i05","Translate 'Good morning, how are you?' into Spanish. Reply with the translation only.", ("contains_all",["Buenos días","cómo est"])),
 ("i06","Write a single sentence that contains the words 'lantern', 'harbour' and 'quietly' in that order.", ("ordered",["lantern","harbour","quietly"])),
 ("i07","Answer with a single integer: how many letters are in the word 'parallelism'?", ("contains_any",["11"])),
 ("i08","Reverse the string 'benchmark' and reply with the result only.", ("regex", r"^\s*kramhcneb\s*$")),
 ("i09","Produce a Markdown table with two columns, 'Unit' and 'Symbol', and exactly three rows: metre, kilogram, second. Nothing else.", ("rubric","header + separator + 3 rows m/kg/s, nothing else")),
 ("i10","Repeat the following sentence exactly, changing nothing: 'Seven quick foxes jumped; none looked back.'", ("regex", r"^\s*'?Seven quick foxes jumped; none looked back\.'?\s*$")),
 ("i11","Give three bullet points about tea. Each bullet must be at most six words.", ("rubric","3 bullets, each <=6 words")),
 ("i12","Write the number 1,234,567 in words. Reply with the words only.", ("contains_all",["one million","two hundred","thirty-four thousand","five hundred","sixty-seven"])),
 ("i13","Respond only with the SHA-256 hash length in hexadecimal characters, as a number.", ("regex", r"^\s*64\s*$")),
 ("i14","Write a limerick about a router. Five lines, nothing else.", ("rubric","5 lines, AABBA-ish, on topic")),
 ("i15","Sort these words alphabetically and reply as a comma-separated list only: pear, apple, mango, banana, kiwi", ("regex", r"^\s*apple,\s*banana,\s*kiwi,\s*mango,\s*pear\s*$")),
]
E = [
 ("e01","Extract every email address from the text and list them one per line, nothing else:\n'Contact ops@example.com or, for billing, billing@example.org. Old address: rick@old.example.net (defunct).'", ("regex", r"^\s*ops@example\.com\s*\n\s*billing@example\.org\s*\n\s*rick@old\.example\.net\s*$")),
 ("e02","From this sentence, what is the total cost? Number only.\n'We bought 3 cables at $4.50 each and 2 adapters at $12.25 each.'", ("contains_any",["38","38.00","38.0"])),
 ("e03","Which items in this list are prime numbers? Reply as a comma-separated list only: 21, 23, 25, 29, 31, 33", ("regex", r"^\s*23,\s*29,\s*31\s*$")),
 ("e04","Given these log timestamps, how many minutes elapsed between the first and last? Number only.\n09:14:05 start\n09:22:41 step\n09:57:05 done", ("contains_any",["43"])),
 ("e05","From the text, list the person's role and employer as 'role @ employer' and nothing else:\n'Jordan Lee has been the lead reliability engineer at Northwind Freight since 2021, after five years at Contoso.'", ("contains_all",["lead reliability engineer","Northwind Freight"])),
 ("e06","Convert this CSV into JSON, an array of objects, no prose:\nname,qty\nbolt,40\nnut,55", ("json_equals",[{"name":"bolt","qty":40},{"name":"nut","qty":55}])),
 ("e07","What is the third word of the second sentence? Reply with the word only.\n'The pump failed early. Engineers replaced the bearing quickly. Service resumed.'", ("regex", r"^\s*the\s*$")),
 ("e08","From the following, how many distinct hostnames appear? Number only.\nweb1 up, db1 up, web1 down, cache3 up, db1 down, web2 up", ("contains_any",["4"])),
 ("e09","Extract the version number from this line and reply with it only: 'llama-server build: b7211 (v0.9.3-rc2) linux x86_64'", ("contains_any",["0.9.3-rc2"])),
 ("e10","Which sentence contains a date? Reply with the sentence number only.\n1. The filter needs cleaning.\n2. We last serviced it on 3 March 2024.\n3. Order a spare next time.", ("regex", r"^\s*2\.?\s*$")),
 ("e11","Sum the numbers in this text and reply with the total only: 'Batch A produced 120 units, batch B 85, batch C 140, and 5 were rejected overall.'", ("contains_any",["350"])),
 ("e12","List the two-letter country codes mentioned, in order of appearance, comma-separated only:\n'Shipments route via DE, then NL, before reaching US customers; returns go to DE.'", ("regex", r"^\s*DE,\s*NL,\s*US(,\s*DE)?\s*$")),
 ("e13","What temperature is mentioned, in Celsius? Number only.\n'The sensor logged 212 °F at the outlet before shutdown.'", ("contains_any",["100"])),
 ("e14","Extract the flags from this command line as a comma-separated list only: `rsync -avz --delete --exclude .git src/ dst/`", ("contains_all",["-avz","--delete","--exclude"])),
 ("e15","Given this dictionary, what is the value for 'gamma'? Reply with the value only.\n{'alpha': 3, 'beta': 7, 'gamma': 11, 'delta': 2}", ("regex", r"^\s*11\s*$")),
]
R = [
 ("r01","A train leaves at 14:35 and arrives at 17:10 the same day. How many minutes is the journey? End with 'ANSWER: <n>'.", ("exact_num",155)),
 ("r02","If a shirt costs $40 after a 20% discount, what was the original price in dollars? End with 'ANSWER: <n>'.", ("exact_num",50)),
 ("r03","What is the smallest positive integer divisible by 6, 8 and 9? End with 'ANSWER: <n>'.", ("exact_num",72)),
 ("r04","Three friends split a bill equally. After each adds a $3 tip, the total paid is $63. What was the bill before tips? End with 'ANSWER: <n>'.", ("exact_num",54)),
 ("r05","A clock shows 3:00. How many degrees are between the hour and minute hands? End with 'ANSWER: <n>'.", ("exact_num",90)),
 ("r06","I am thinking of a two-digit number. Its digits sum to 11 and the tens digit is 3 more than the units digit. What is the number? End with 'ANSWER: <n>'.", ("exact_num",74)),
 ("r07","A bacteria colony doubles every 20 minutes. Starting from 500, how many after 2 hours? End with 'ANSWER: <n>'.", ("exact_num",32000)),
 ("r08","In a room of 30 people, 18 like tea, 15 like coffee, and 6 like neither. How many like both? End with 'ANSWER: <n>'.", ("exact_num",9)),
 ("r09","What is 17 squared minus 13 squared? End with 'ANSWER: <n>'.", ("exact_num",120)),
 ("r10","A rope is cut into two pieces in the ratio 3:5. The longer piece is 45 cm. How long was the rope? End with 'ANSWER: <n>'.", ("exact_num",72)),
 ("r11","If today is Wednesday, what day of the week will it be 100 days from now? End with 'ANSWER: <day>'.", ("contains_any",["ANSWER: Friday"])),
 ("r12","Dana is older than Eli. Eli is older than Fay. Fay is older than Gus. Who is the second youngest? End with 'ANSWER: <name>'.", ("contains_any",["ANSWER: Fay"])),
 ("r13","A box has 4 red and 6 blue balls. Two are drawn without replacement. What is the probability both are red, as a fraction in lowest terms? End with 'ANSWER: <a/b>'.", ("contains_any",["ANSWER: 2/15"])),
 ("r14","How many ways can you arrange the letters of the word 'LEVEL'? End with 'ANSWER: <n>'.", ("exact_num",30)),
 ("r15","A password must be 4 digits with no digit repeated and cannot start with 0. How many such passwords exist? End with 'ANSWER: <n>'.", ("exact_num",4536)),
]
P = [(pid,"knowledge",q,c) for pid,q,c in K]+[(pid,"instruction",q,c) for pid,q,c in I]+[(pid,"extraction",q,c) for pid,q,c in E]+[(pid,"reasoning",q,c) for pid,q,c in R]
